module.exports = [{
        firstName: 'Charles',
        lastName: 'Spurgeon',
        country: 'England',
        yearOfBirth: '1834',
        yearOfDeath: '1892',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'x',
    },
    {
        firstName: 'Kenneth',
        lastName: 'Hagin',
        country: '70',
        yearOfBirth: '1900',
        yearOfDeath: '',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'x',
    },
    {
        firstName: 'T.L.',
        lastName: 'Osborn',
        country: '70',
        yearOfBirth: '1900',
        yearOfDeath: '',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'x',
    },
    {
        firstName: 'Billy',
        lastName: 'Graham',
        country: '70',
        yearOfBirth: '1900',
        yearOfDeath: '',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'',
    },
    {
        firstName: 'David',
        lastName: 'Oyedepo',
        country: '70',
        yearOfBirth: '1981',
        yearOfDeath: '',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'',
    },
];

// firstName: String,
//     lastName: String,
//     country: String,
//     yearOfBirth: String,
//     yearOfDeath: String,
//     addedByUserId: String,
//     preacherPhoto: String,