module.exports = [{
        firstName: 'Charles',
        lastName: 'Spurgeon',
        country: 'England',
        yearOfBirth: '1834',
        yearOfDeath: '1892',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/LDxCntC.png',
        assignedId:'1',
    },
    {
        firstName: 'Kenneth',
        lastName: 'Hagin',
        country: 'United States of America',
        yearOfBirth: '1917',
        yearOfDeath: '2003',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/KRjVvpL.jpg',
        assignedId:'2',
    },
    {
        firstName: 'T.L.',
        lastName: 'Osborn',
        country: 'United States of America',
        yearOfBirth: '1923',
        yearOfDeath: '2003',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/VHfSBLm.jpg',
        assignedId:'3',
    },
    {
        firstName: 'Billy',
        lastName: 'Graham',
        country: 'United States of America',
        yearOfBirth: '1918',
        yearOfDeath: '2018',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/UYo6HJb.jpg',
        assignedId:'4',
    },
    {
        firstName: 'David',
        lastName: 'Oyedepo',
        country: 'Nigeria',
        yearOfBirth: '1954',
        yearOfDeath: '',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/v341ABw.jpg',
        assignedId:'5',
    },
    {
        firstName: 'Smith',
        lastName: 'Wigglesworth',
        country: 'England',
        yearOfBirth: '1859',
        yearOfDeath: '1947',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/F2rOygH.jpg',
        assignedId:'6',
    },
];

// firstName: String,
//     lastName: String,
//     country: String,
//     yearOfBirth: String,
//     yearOfDeath: String,
//     addedByUserId: String,
//     preacherPhoto: String,