module.exports = [{
        firstName: 'Charles',
        lastName: 'Spurgeon',
        country: 'England',
        yearOfBirth: '1834',
        yearOfDeath: '1892',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/KdHi5gI.jpg',
    },
    {
        firstName: 'Kenneth',
        lastName: 'Hagin',
        country: 'United States of America',
        yearOfBirth: '1917',
        yearOfDeath: '2003',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/tqUudYj.jpg',
    },
    {
        firstName: 'T.L.',
        lastName: 'Osborn',
        country: '70',
        yearOfBirth: '1923',
        yearOfDeath: '2003',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/1b2DuJg.jpg',
    },
    {
        firstName: 'Billy',
        lastName: 'Graham',
        country: '70',
        yearOfBirth: '1918',
        yearOfDeath: '2018',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/qSIOfwA.jpg',
    },
    {
        firstName: 'David',
        lastName: 'Oyedepo',
        country: 'Nigeria',
        yearOfBirth: '1954',
        yearOfDeath: '',
        addedByUserId:'Obi Nwokogba',
        preacherPhoto:'https://i.imgur.com/3nJMkss.jpg',
    },
];

// firstName: String,
//     lastName: String,
//     country: String,
//     yearOfBirth: String,
//     yearOfDeath: String,
//     addedByUserId: String,
//     preacherPhoto: String,